# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2dd39a4b3beb8c500f3262fc23ff590e42bb61cb6a41428062add62502738b1186434870c531276cb31e39765e12b711a65bf0c73568665324bf6e5f55999d99

test:
  secret_key_base: 098b87c1df500602b8075c15f542ec8de4495367d11b7f5ac7cc3d33ce0ebe6de66cd81033cd961ad9998d2baa96c77431fff312a13c71288c3d9b4b16265ade

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
